apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: znn8iaj9w-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/znn8iaj9w-java-quarkus-gitops